language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codeclimate-test-reporter
  - pip install gunicorn

before_script:
 - psql -c 'create database testdb;' -U postgres
script: 
  - coverage run --source=api manage.py test
  - coverage report -m
after_success:
 - coveralls
 - codeclimate-test-reporter


  
  
